# Generated by Django 3.1.5 on 2021-01-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210109_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='employee_identification',
            new_name='employee_id',
        ),
    ]
