# Generated by Django 3.1.5 on 2021-01-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20210111_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
